-- Tier list real de ataque (7 estrelas). 326 campeoes.
--
-- GERADO por supabase/gerar_seed_tier_list.py — nao edite a mao. A fonte e a
-- planilha do dono cruzada com o mcoc.app; reveja la e regenere este arquivo.
--
-- Idempotente e REEXECUTAVEL: casa por nome e sobrescreve classe, nota, sig
-- recomendado, nome em ingles e a flag de 7 estrelas. E o mecanismo de
-- atualizacao da tier list — quando as fontes revisarem as notas, regenere e
-- rode de novo. Os ids nao mudam, entao os rosters continuam apontando para
-- os mesmos campeoes.
--
-- Nao apaga nada: um campeao que saia das fontes permanece no catalogo.
--
-- ORDEM: exige a migration 007 (name_en, has_7star). Se as linhas de amostra
-- de seed_dev.sql ainda estiverem na tabela, rode limpeza_seed_dev.sql antes —
-- a grafia delas difere ("Serpente" vs "O serpente") e o ON CONFLICT (name)
-- nao as alcancaria, duplicando o catalogo.
--
-- COMO AS NOTAS FORAM OBTIDAS
-- Media 50/50 do percentil de duas tier lists independentes: a do dono e a do
-- mcoc.app (letras S+..F, ela propria consenso de dois criadores). Percentil e
-- nao nota crua porque as escalas diferem — comparar "9,5" com "S" nao teria
-- significado. As faixas mantiveram o tamanho original, entao mudou quem esta
-- em cada uma, nao quantas vagas ela tem.
--
-- Excecao: onde o mcoc.app promove um campeao que ele mesmo marca como
-- high_skill, o bonus e descontado e vale so a nota do dono. O perfil de jogo
-- e Valiant sem Battlegrounds nem Guerra de Alianca, onde teto de performance
-- rende menos que utilidade pratica.
--
-- Faixas: Top of the Class 31, Incredible 58, Fantastic 80, Great 48, Very Good 39, Good 13, Mediocre 39, Awful 18.
-- Sem versao 7 estrelas (has_7star = false): 13.

INSERT INTO base_champions
  (name, champion_class, attack_tier_score, attack_recommended_sig, name_en, has_7star)
VALUES
  ('O serpente',                        'Cosmic',   10,    200,  'The Serpent',                    true),
  ('Karolina Dean',                     'Cosmic',   10,    200,  'Karolina Dean',                  true),
  ('Thanos (Imortal)',                  'Cosmic',   10,    200,  'Thanos (Deathless)',             true),
  ('Hulkling',                          'Cosmic',   10,    20,   'Hulkling',                       true),
  ('Vox',                               'Cosmic',   9.5,   20,   'Vox',                            true),
  ('Angela',                            'Cosmic',   9.5,   200,  'Angela',                         true),
  ('Bastião',                           'Tech',     10,    200,  'Bastion',                        true),
  ('Yondu',                             'Tech',     9.5,   20,   'Yondu',                          true),
  ('Gatuno',                            'Tech',     10,    200,  'Prowler',                        true),
  ('Escorpião',                         'Science',  10,    20,   'Scorpion',                       true),
  ('Mulher-Aranha (Jessica Drew)',      'Science',  10,    200,  'Spider-Woman (Jessica Drew)',    true),
  ('Conde Nefaria',                     'Science',  10,    20,   'Count Nefaria',                  true),
  ('Massacre',                          'Mutant',   10,    0,    'Onslaught',                      true),
  ('Senhor Sinistro',                   'Mutant',   10,    200,  'Mister Sinister',                true),
  ('Jean Grey',                         'Mutant',   10,    200,  'Jean Grey',                      true),
  ('Kitty Pryde',                       'Mutant',   10,    200,  'Kitty Pryde',                    true),
  ('Arcanjo',                           'Mutant',   10,    200,  'Archangel',                      true),
  ('Doutor Estranho',                   'Mystic',   10,    200,  'Doctor Strange',                 true),
  ('Mojo',                              'Mystic',   10,    200,  'Mojo',                           true),
  ('Hood',                              'Mystic',   9.5,   200,  'The Hood',                       true),
  ('Madelyne Pryor',                    'Mystic',   10,    20,   'Madelyne Pryor',                 true),
  ('Nico Minoru',                       'Mystic',   10,    200,  'Nico Minoru',                    true),
  ('Kushala',                           'Mystic',   10,    200,  'Kushala',                        true),
  ('Espiral',                           'Mystic',   9.5,   200,  'Spiral',                         true),
  ('Okoye',                             'Skill',    10,    20,   'Okoye',                          true),
  ('Ossos Cruzados',                    'Skill',    10,    200,  'Crossbones',                     true),
  ('Doutor Bong',                       'Skill',    10,    200,  'Doctor Bong',                    true),
  ('Rei do Crime',                      'Skill',    10,    200,  'Kingpin',                        true),
  ('Lumatrix',                          'Skill',    10,    20,   'Lumatrix',                       true),
  ('Valquíria',                         'Skill',    9.5,   200,  'Valkyrie',                       true),
  ('Patriota',                          'Skill',    9,     20,   'Patriot',                        true),
  ('Phyla-Vell',                        'Cosmic',   9,     200,  'Phyla-Vell',                     true),
  ('Knull',                             'Cosmic',   9.5,   200,  'Knull',                          true),
  ('Medusa',                            'Cosmic',   9.5,   20,   'Medusa',                         true),
  ('Fênix Negra',                       'Cosmic',   9.5,   200,  'Dark Phoenix',                   true),
  ('Homem de Ferro Superior',           'Cosmic',   9,     0,    'Superior Iron Man',              true),
  ('Bill Raio Beta',                    'Cosmic',   9,     200,  'Beta Ray Bill',                  true),
  ('Corvus Glaive',                     'Cosmic',   9,     20,   'Corvus Glaive',                  true),
  ('Visão (Aarkus)',                    'Cosmic',   9,     0,    'Vision (Aarkus)',                true),
  ('Cull Obsidian',                     'Cosmic',   9.5,   20,   'Cull Obsidian',                  true),
  ('Hyperion',                          'Cosmic',   9,     20,   'Hyperion',                       true),
  ('Imperiosa',                         'Cosmic',   9,     20,   'Imperiosa',                      true),
  ('Venom',                             'Cosmic',   9,     20,   'Venom',                          true),
  ('Heimdall',                          'Cosmic',   9.5,   20,   'Heimdall',                       true),
  ('Adam Warlock',                      'Cosmic',   9,     0,    'Adam Warlock',                   true),
  ('Gladiador',                         'Cosmic',   9,     200,  'Gladiator',                      true),
  ('Grito',                             'Cosmic',   9,     0,    'Scream',                         true),
  ('Superskrull',                       'Cosmic',   9,     0,    'Super-Skrull',                   true),
  ('Gorr',                              'Cosmic',   9,     20,   'Gorr',                           true),
  ('Motoqueiro Fantasma Cósmico',       'Cosmic',   9,     20,   'Cosmic Ghost Rider',             false),
  ('Hércules',                          'Cosmic',   9.5,   200,  'Hercules',                       false),
  ('Galan',                             'Cosmic',   9.5,   20,   'Galan',                          true),
  ('Fênix',                             'Cosmic',   8.5,   200,  'Phoenix',                        true),
  ('Odin',                              'Cosmic',   8.5,   0,    'Odin',                           true),
  ('Maestro',                           'Cosmic',   8.5,   0,    'Maestro',                        true),
  ('Venom, o pato',                     'Cosmic',   8.5,   0,    'Venom the Duck',                 true),
  ('Rei Groot (Imortal)',               'Cosmic',   8.5,   0,    'King Groot (Deathless)',         true),
  ('Sersi',                             'Cosmic',   8.5,   20,   'Sersi',                          true),
  ('Gamora',                            'Cosmic',   8.5,   0,    'Gamora',                         true),
  ('Nova',                              'Cosmic',   8.5,   200,  'Nova',                           true),
  ('Capitã Marvel',                     'Cosmic',   8,     200,  'Captain Marvel (Movie)',         true),
  ('Terrax',                            'Cosmic',   8,     200,  'Terrax',                         true),
  ('Surfista Prateado',                 'Cosmic',   8,     0,    'Silver Surfer',                  true),
  ('Rei Groot',                         'Cosmic',   7.25,  200,  'King Groot',                     true),
  ('Venompool',                         'Cosmic',   8,     0,    'Venompool',                      true),
  ('Thor',                              'Cosmic',   7.25,  200,  'Thor',                           true),
  ('Campeão do Universo',               'Cosmic',   8,     200,  'The Champion',                   true),
  ('Duende Vermelho',                   'Cosmic',   7.25,  0,    'Red Goblin',                     true),
  ('Aniquilador',                       'Cosmic',   7.25,  0,    'Annihilus',                      true),
  ('Ronan, o acusador',                 'Cosmic',   7.25,  200,  'Ronan',                          false),
  ('Proxima Midnight',                  'Cosmic',   5.75,  20,   'Proxima Midnight',               true),
  ('Miss Marvel (Kamala Khan)',         'Cosmic',   5.75,  20,   'Ms. Marvel (Kamala Khan)',       true),
  ('Carnificina',                       'Cosmic',   8,     20,   'Carnage',                        true),
  ('Hela',                              'Cosmic',   5.75,  20,   'Hela',                           true),
  ('Ikaris',                            'Cosmic',   5.75,  0,    'Ikaris',                         true),
  ('Andarilho dos Céus',                'Cosmic',   5.75,  0,    'Air-Walker',                     true),
  ('Homem-Aranha (Simbionte)',          'Cosmic',   5.75,  20,   'Spider-Man (Symbiote)',          true),
  ('Drax, o destruidor',                'Cosmic',   5.75,  20,   'Drax',                           true),
  ('Capitã Marvel (Clássica)',          'Cosmic',   2.5,   0,    'Captain Marvel (Classic)',       true),
  ('Raio Negro',                        'Cosmic',   2.5,   20,   'Black Bolt',                     true),
  ('Thanos',                            'Cosmic',   2.5,   0,    'Thanos',                         true),
  ('Groot',                             'Cosmic',   2.5,   0,    'Groot',                          true),
  ('Miss Marvel',                       'Cosmic',   2.5,   0,    'Ms. Marvel',                     true),
  ('Caça-aranhas (J. J. J.)',           'Tech',     9.5,   0,    'Spider-Slayer (J. Jonah Jameson)',true),
  ('Warlock',                           'Tech',     9.5,   200,  'Warlock',                        true),
  ('Sentinela',                         'Tech',     9.5,   0,    'Sentinel',                       true),
  ('Coração de Ferro',                  'Tech',     9.5,   0,    'Ironheart',                      true),
  ('Homem-aranha (Aprimorado pelo Stark)', 'Tech',     10,    60,   'Spider-Man (Stark Enhanced)',    true),
  ('Jack O''Lantern',                   'Tech',     9.5,   0,    'Jack O''Lantern',                true),
  ('Viv Vision',                        'Tech',     9.5,   200,  'Viv Vision',                     true),
  ('Shuri',                             'Tech',     9.5,   20,   'Shuri',                          true),
  ('Solvarch',                          'Tech',     10,    20,   'Solvarch',                       true),
  ('Homem-Formiga (Futuro)',            'Tech',     9.5,   200,  'Ant-Man (Future)',               true),
  ('Guardião',                          'Tech',     9.5,   200,  'Guardian',                       true),
  ('O Criador',                         'Tech',     9.5,   0,    'The Maker',                      true),
  ('Ruby Thursday',                     'Tech',     9,     200,  'Ruby Thursday',                  true),
  ('Nimrod',                            'Tech',     9,     200,  'Nimrod',                         true),
  ('Peni Parker',                       'Tech',     9,     20,   'Peni Parker',                    true),
  ('Duende Macabro (Phil Urich)',       'Tech',     8.5,   20,   'Hobgoblin',                      true),
  ('Shocker',                           'Tech',     9,     200,  'Shocker',                        true),
  ('Fantasma',                          'Tech',     9.5,   200,  'Ghost',                          false),
  ('Caveira Vermelha',                  'Tech',     9.5,   0,    'Red Skull',                      true),
  ('Sentinela Ômega',                   'Tech',     9,     20,   'Omega Sentinel',                 true),
  ('Homem de Ferro',                    'Tech',     9,     20,   'Iron Man',                       true),
  ('Homem de Ferro (Infame)',           'Tech',     9,     200,  'Iron Man (Infamous)',            true),
  ('Arnim Zola',                        'Tech',     9,     20,   'Arnim Zola',                     true),
  ('Ultron',                            'Tech',     9,     200,  'Ultron',                         true),
  ('Lady Deathstrike',                  'Tech',     8.5,   200,  'Lady Deathstrike',               true),
  ('Howard, o pato',                    'Tech',     9,     20,   'Howard the Duck',                true),
  ('Arcade',                            'Tech',     8.5,   0,    'Arcade',                         true),
  ('Rocky Racum',                       'Tech',     8.5,   20,   'Rocket Raccoon',                 true),
  ('Hulkbuster',                        'Tech',     8.5,   0,    'Hulkbuster',                     true),
  ('Justiceiro 2099',                   'Tech',     8.5,   20,   'Punisher 2099',                  true),
  ('Visão (Imortal)',                   'Tech',     8,     0,    'Vision (Deathless)',             true),
  ('Capitão América (Sam Wilson)',      'Tech',     8.5,   0,    'Captain America (Sam Wilson)',   true),
  ('Senhor das Estrelas',               'Tech',     8,     200,  'Star-Lord',                      true),
  ('Nebulosa',                          'Tech',     8,     0,    'Nebula',                         true),
  ('Visão',                             'Tech',     7.25,  200,  'Vision',                         true),
  ('Doutor Octopus',                    'Tech',     8,     20,   'Doctor Octopus',                 false),
  ('Mystério',                          'Tech',     8.5,   20,   'Mysterio',                       true),
  ('Visão (Era de Ultron)',             'Tech',     5.75,  200,  'Vision (Age of Ultron)',         true),
  ('Guillotine 2099',                   'Tech',     8.5,   200,  'Guillotine 2099',                true),
  ('Centurião de Prata',                'Tech',     7.25,  20,   'Silver Centurion',               true),
  ('Guerreiro Civil',                   'Tech',     7.25,  0,    'Civil Warrior',                  true),
  ('Homem de Ferro (Guerra infinita)',  'Tech',     7.25,  20,   'Iron Man (Infinity War)',        true),
  ('Darkhawk',                          'Tech',     5.75,  20,   'Darkhawk',                       false),
  ('Homem-Psico',                       'Tech',     5.75,  20,   'Psycho-Man',                     true),
  ('Abutre',                            'Tech',     5.75,  20,   'Vulture',                        true),
  ('Kang, o conquistador',              'Tech',     5.75,  0,    'Kang',                           true),
  ('Máquina de Combate',                'Tech',     5.75,  20,   'War Machine',                    true),
  ('Duende Verde',                      'Tech',     5.75,  20,   'Green Goblin',                   true),
  ('Ultron (Clássico)',                 'Tech',     2.5,   20,   'Ultron (Classic)',               true),
  ('Patriota de Ferro',                 'Tech',     2.5,   20,   'Iron Patriot',                   true),
  ('Vácuo',                             'Science',  9,     200,  'Void',                           true),
  ('Guardião Vermelho',                 'Science',  9.5,   200,  'Red Guardian',                   true),
  ('Onda',                              'Science',  9.5,   200,  'Wave',                           true),
  ('Titânia',                           'Science',  9.5,   20,   'Titania',                        true),
  ('Fóton',                             'Science',  10,    200,  'Photon',                         true),
  ('O Tocha Humana',                    'Science',  10,    0,    'Human Torch',                    true),
  ('Teia de Seda',                      'Science',  9.5,   20,   'Silk',                           true),
  ('Anti-venom',                        'Science',  9.5,   20,   'Anti-Venom',                     true),
  ('Lagarto',                           'Science',  9.5,   200,  'Lizard',                         true),
  ('Mulher-Hulk (Imortal)',             'Science',  9.5,   0,    'She-Hulk (Deathless)',           true),
  ('Luke Cage',                         'Science',  9.5,   20,   'Luke Cage',                      true),
  ('Homem-Aranha 2099',                 'Science',  9,     200,  'Spider-Man 2099',                true),
  ('O Líder',                           'Science',  9,     20,   'The Leader',                     true),
  ('Vigilante',                         'Science',  9,     0,    'Sentry',                         true),
  ('Homem-Areia',                       'Science',  9.5,   200,  'Sandman',                        true),
  ('Porco-Aranha',                      'Science',  9,     20,   'Spider-Ham',                     true),
  ('Marvel Azul',                       'Science',  9,     20,   'Blue Marvel',                    true),
  ('Hulk',                              'Science',  9,     20,   'Hulk',                           true),
  ('Cassie Lang',                       'Science',  9,     20,   'Cassie Lang',                    true),
  ('Falcão (Joaquin Torres)',           'Science',  9,     200,  'Falcon (Joaquín Torres)',        true),
  ('Capitão América (Guerra Infinita)', 'Science',  9,     200,  'Captain America (Infinity War)', true),
  ('Punk-Aranha',                       'Science',  9,     20,   'Spider-Punk',                    true),
  ('Mancha',                            'Science',  9,     200,  'Spot',                           true),
  ('O Supervisor',                      'Science',  9,     200,  'The Overseer',                   true),
  ('Abominável (Imortal)',              'Science',  9,     60,   'Abomination (Immortal)',         true),
  ('Mercúrio',                          'Science',  9,     20,   'Quicksilver',                    true),
  ('Senhor Negativo',                   'Science',  8.5,   60,   'Mister Negative',                true),
  ('Morbius',                           'Science',  8.5,   60,   'Morbius',                        true),
  ('Homem-Aranha (Miles Morales)',      'Science',  8,     200,  'Spider-Man (Miles Morales)',     true),
  ('Mulher-Hulk',                       'Science',  8.5,   20,   'She-Hulk',                       true),
  ('Gwen-Aranha',                       'Science',  8.5,   0,    'Spider-Gwen',                    true),
  ('Alto Evolucionário',                'Science',  8.5,   200,  'High Evolutionary',              true),
  ('Joe Fixit',                         'Science',  8.5,   20,   'Joe Fixit',                      true),
  ('Homem-Formiga',                     'Science',  8.5,   20,   'Ant-Man',                        true),
  ('Jessica Jones',                     'Science',  8,     0,    'Jessica Jones',                  true),
  ('Hulk Vermelho',                     'Science',  8,     20,   'Red Hulk',                       true),
  ('Tremor',                            'Science',  8,     0,    'Quake',                          false),
  ('M.O.D.O.K.',                        'Science',  8,     0,    'M.O.D.O.K.',                     true),
  ('O Coisa',                           'Science',  8,     200,  'Thing',                          true),
  ('Senhor Fantástico',                 'Science',  8.5,   80,   'Mister Fantastic',               true),
  ('Homem-Aranha (Clássico)',           'Science',  8,     20,   'Spider-Man (Classic)',           true),
  ('Rino',                              'Science',  8,     0,    'Rhino',                          true),
  ('Hulk (Imortal)',                    'Science',  7.25,  0,    'Hulk (Immortal)',                true),
  ('Jaqueta-Amarela',                   'Science',  5.75,  200,  'Yellowjacket',                   true),
  ('Vespa',                             'Science',  5.75,  0,    'Wasp',                           true),
  ('Mulher Invisível',                  'Science',  8,     0,    'Invisible Woman',                true),
  ('Hulk (Ragnarok)',                   'Science',  5.75,  0,    'Hulk (Ragnarok)',                true),
  ('Abominável',                        'Science',  5.75,  0,    'Abomination',                    true),
  ('Electro',                           'Science',  5.75,  0,    'Electro',                        true),
  ('Capitão América (WWII)',            'Science',  2.5,   0,    'Captain America (WWII)',         true),
  ('Capitão América',                   'Science',  2.5,   0,    'Captain America',                true),
  ('Capitã Britânia',                   'Mutant',   10,    200,  'Captain Britain',                true),
  ('Cristal',                           'Mutant',   9.5,   200,  'Dazzler',                        true),
  ('Deadpool (X-force)',                'Mutant',   9.5,   0,    'Deadpool (X-Force)',             true),
  ('Pó',                                'Mutant',   9.5,   200,  'Dust',                           true),
  ('Pixie',                             'Mutant',   9,     20,   'Pixie',                          true),
  ('Gentil',                            'Mutant',   9.5,   200,  'Gentle',                         true),
  ('Shatterstar',                       'Mutant',   9,     200,  'Shatterstar',                    true),
  ('Homem de Gelo',                     'Mutant',   9,     200,  'Iceman',                         true),
  ('Wolverine (X-23)',                  'Mutant',   8.5,   20,   'Wolverine (X-23)',               true),
  ('Cassandra Nova',                    'Mutant',   9,     200,  'Cassandra Nova',                 true),
  ('Emma Frost',                        'Mutant',   9,     20,   'Emma Frost',                     true),
  ('Ciclope (Equipe azul)',             'Mutant',   9,     200,  'Cyclops (Blue Team)',            true),
  ('Professor X',                       'Mutant',   9,     20,   'Professor X',                    true),
  ('Samurai de Prata',                  'Mutant',   9,     200,  'Silver Samurai',                 true),
  ('Havok',                             'Mutant',   9,     200,  'Havok',                          true),
  ('Groxo',                             'Mutant',   8.5,   20,   'Toad',                           true),
  ('Dominó',                            'Mutant',   9,     200,  'Domino',                         true),
  ('Míssil Adolescente Megassônico',    'Mutant',   9,     0,    'Negasonic Teenage Warhead',      true),
  ('Apocalipse',                        'Mutant',   9,     0,    'Apocalypse',                     true),
  ('Dani Moonstar',                     'Mutant',   9,     60,   'Dani Moonstar',                  true),
  ('Mancha Solar',                      'Mutant',   9,     200,  'Sunspot',                        true),
  ('Tempestade (Pirâmide X)',           'Mutant',   9,     200,  'Storm (Pyramid X)',              true),
  ('Colossus',                          'Mutant',   8.5,   20,   'Colossus',                       true),
  ('Noturno',                           'Mutant',   8.5,   200,  'Nightcrawler',                   true),
  ('Magneto',                           'Mutant',   9,     0,    'Magneto',                        false),
  ('Ômega Red',                         'Mutant',   8.5,   200,  'Omega Red',                      true),
  ('Tempestade',                        'Mutant',   8.5,   0,    'Storm',                          true),
  ('Vampira',                           'Mutant',   8,     20,   'Rogue',                          true),
  ('Estrela Polar',                     'Mutant',   8.5,   0,    'Northstar',                      true),
  ('Bispo',                             'Mutant',   8.5,   60,   'Bishop',                         true),
  ('Gambit',                            'Mutant',   8,     20,   'Gambit',                         true),
  ('Namor',                             'Mutant',   8.5,   200,  'Namor',                          true),
  ('Magneto (Dinastia X)',              'Mutant',   8,     0,    'Magneto (House of X)',           true),
  ('Sauron',                            'Mutant',   8,     0,    'Sauron',                         true),
  ('Cable',                             'Mutant',   8,     0,    'Cable',                          true),
  ('Conflyto',                          'Mutant',   8,     20,   'Stryfe',                         true),
  ('Wolverine (Arma X)',                'Mutant',   8,     0,    'Wolverine (Weapon X)',           true),
  ('Dente-de-Sabre',                    'Mutant',   8,     0,    'Sabretooth',                     true),
  ('Wolverine',                         'Mutant',   5.75,  20,   'Wolverine',                      true),
  ('Goldpool',                          'Mutant',   5.75,  0,    'Goldpool',                       true),
  ('Jubileu',                           'Mutant',   5.75,  20,   'Jubilee',                        true),
  ('Psylocke',                          'Mutant',   5.75,  20,   'Psylocke',                       true),
  ('Platinumpool',                      'Mutant',   5.75,  0,    'Platinumpool',                   true),
  ('Deadpool',                          'Mutant',   5.75,  20,   'Deadpool',                       true),
  ('Velho Logan',                       'Mutant',   2.5,   20,   'Old Man Logan',                  true),
  ('Fera',                              'Mutant',   2.5,   20,   'Beast',                          true),
  ('Ciclope (Nova escola Xavier)',      'Mutant',   2.5,   0,    'Cyclops (New Xavier School)',    true),
  ('Motoqueiro Fantasma',               'Mystic',   9.5,   200,  'Ghost Rider',                    true),
  ('Homem-Absorvente',                  'Mystic',   9.5,   200,  'Absorbing Man',                  true),
  ('Homem-Aranha (Pavitr Prabhakar)',   'Mystic',   10,    20,   'Spider-Man (Pavitr Prabhakar)',  true),
  ('Magia',                             'Mystic',   9.5,   200,  'Magik',                          true),
  ('Purgatório',                        'Mystic',   9.5,   60,   'Purgatory',                      true),
  ('Shathra',                           'Mystic',   9.5,   0,    'Shathra',                        true),
  ('Simbionte Supremo',                 'Mystic',   9.5,   0,    'Symbiote Supreme',               true),
  ('Lobisomen na Noite',                'Mystic',   9.5,   20,   'Werewolf By Night',              true),
  ('Tigresa',                           'Mystic',   9.5,   200,  'Tigra',                          true),
  ('Homem-Coisa',                       'Mystic',   9,     20,   'Man-Thing',                      true),
  ('Doutor Voodoo',                     'Mystic',   9,     200,  'Doctor Voodoo',                  true),
  ('America Chavez',                    'Mystic',   9,     20,   'America Chavez',                 true),
  ('Tigresa Branca',                    'Mystic',   9,     200,  'White Tiger',                    true),
  ('Diablo',                            'Mystic',   9,     20,   'Diablo',                         true),
  ('Blade (Forjado)',                   'Mystic',   9,     200,  'Blade (Stellar Forged)',         true),
  ('Viúva Negra (Claire Voyant)',       'Mystic',   9,     0,    'Black Widow (Claire Voyant)',    true),
  ('Longshot',                          'Mystic',   9,     20,   'Longshot',                       true),
  ('Thor (Jane Foster)',                'Mystic',   9,     20,   'Thor (Jane Foster)',             true),
  ('Fanático',                          'Mystic',   9.5,   20,   'Juggernaut',                     true),
  ('Rintrah',                           'Mystic',   9,     20,   'Rintrah',                        true),
  ('Drácula',                           'Mystic',   8.5,   0,    'Dracula',                        true),
  ('Doutor Destino',                    'Mystic',   9.5,   200,  'Doctor Doom',                    false),
  ('Kindred',                           'Mystic',   9,     60,   'Kindred',                        true),
  ('Wong',                              'Mystic',   8.5,   20,   'Wong',                           true),
  ('O Destruidor',                      'Mystic',   8.5,   200,  'The Destroyer',                  true),
  ('Guillotine (Deathless)',            'Mystic',   8,     0,    'Guillotine (Deathless)',         true),
  ('Isofine',                           'Mystic',   8.5,   200,  'Isophyne',                       true),
  ('Feiticeira Escarlate',              'Mystic',   8.5,   0,    'Scarlet Witch',                  true),
  ('Wiccano',                           'Mystic',   8.5,   20,   'Wiccan',                         true),
  ('Encantor',                          'Mystic',   8.5,   200,  'Enchantress',                    true),
  ('Feiticeira Escarlate (Clássica)',   'Mystic',   8,     200,  'Scarlet Witch (Classic)',        true),
  ('Ebony Maw',                         'Mystic',   8,     20,   'Ebony Maw',                      true),
  ('Homem-Dragão',                      'Mystic',   8,     0,    'Dragon Man',                     true),
  ('Homem-Aranha (Supremo)',            'Mystic',   8,     0,    'Spider-Man (Supreme)',           true),
  ('Maga Suprema',                      'Mystic',   8,     0,    'Sorcerer Supreme',               true),
  ('Mefisto',                           'Mystic',   8,     200,  'Mephisto',                       false),
  ('Sasquatch',                         'Mystic',   8.5,   60,   'Sasquatch',                      true),
  ('Mordo',                             'Mystic',   8.5,   20,   'Mordo',                          true),
  ('Mangog',                            'Mystic',   5.75,  0,    'Mangog',                         true),
  ('Guillotine',                        'Mystic',   5.75,  20,   'Guillotine',                     true),
  ('Dormammu',                          'Mystic',   5.75,  20,   'Dormammu',                       true),
  ('Morningstar',                       'Mystic',   5.75,  20,   'Morningstar',                    true),
  ('Loki',                              'Mystic',   5.75,  20,   'Loki',                           true),
  ('Punho de Ferro',                    'Mystic',   2.5,   20,   'Iron Fist',                      true),
  ('Punho de Ferro (Imortal)',          'Mystic',   2.5,   20,   'Iron Fist (Immortal)',           true),
  ('Colossus Imparável',                'Mystic',   2.5,   0,    'Unstoppable Colossus',           true),
  ('Falcão',                            'Skill',    9,     60,   'Falcon',                         true),
  ('Gata Negra',                        'Skill',    9.5,   20,   'Black Cat',                      true),
  ('Toupeira',                          'Skill',    9.5,   20,   'Mole Man',                       true),
  ('Chee''ilth',                        'Skill',    9.5,   20,   'Chee''ilth',                     true),
  ('Tarântula Negra',                   'Skill',    9.5,   200,  'Black Tarantula',                true),
  ('Barão Zemo',                        'Skill',    9.5,   20,   'Baron Zemo',                     true),
  ('Mercenário',                        'Skill',    9.5,   0,    'Bullseye',                       true),
  ('Kate Bishop',                       'Skill',    9.5,   200,  'Kate Bishop',                    false),
  ('Nick Fury',                         'Skill',    10,    200,  'Nick Fury',                      true),
  ('Pantera Jabari',                    'Skill',    9,     20,   'Jabari Panther',                 true),
  ('Shang-Chi',                         'Skill',    9.5,   20,   'Shang-Chi',                      true),
  ('Justiceiro',                        'Skill',    9,     60,   'Punisher',                       true),
  ('Yelena Belova',                     'Skill',    9,     200,  'Yelena Belova',                  true),
  ('Thor (Ragnarok)',                   'Skill',    9,     200,  'Thor (Ragnarok)',                true),
  ('Senhor das Estrelas (Forjado)',     'Skill',    9,     20,   'Star-Lord (Stellar Forged)',     true),
  ('Senhor Cavaleiro',                  'Skill',    9,     200,  'Mr. Knight',                     true),
  ('Mantis',                            'Skill',    9,     20,   'Mantis',                         true),
  ('M''Baku',                           'Skill',    8.5,   20,   'M''Baku',                        true),
  ('Pantera Negra (Guerra Civil)',      'Skill',    9.5,   200,  'Black Panther (Civil War)',      true),
  ('Homem-Aranha (Traje Furtivo)',      'Skill',    9.5,   60,   'Spider-Man (Stealth Suit)',      true),
  ('Blade',                             'Skill',    9,     200,  'Blade',                          true),
  ('Attuma',                            'Skill',    9,     200,  'Attuma',                         true),
  ('Franken-Castle',                    'Skill',    9,     80,   'Franken-Castle',                 true),
  ('Aegon',                             'Skill',    9,     200,  'Aegon',                          false),
  ('Sabre de Prata',                    'Skill',    8.5,   0,    'Silver Sable',                   true),
  ('Hit-Monkey',                        'Skill',    9,     0,    'Hit-Monkey',                     true),
  ('Viúva Negra (Origem Letal)',        'Skill',    8.5,   0,    'Black Widow (Deadly Origin)',    true),
  ('Killmonger',                        'Skill',    8,     200,  'Killmonger',                     true),
  ('Masacre',                           'Skill',    8.5,   0,    'Masacre',                        true),
  ('O Espancador',                      'Skill',    8,     20,   'Night Thrasher',                 true),
  ('Agente Venom',                      'Skill',    8,     0,    'Agent Venom',                    false),
  ('Serpente da Lua',                   'Skill',    8,     60,   'Moondragon',                     true),
  ('Elsa Bloodstone',                   'Skill',    8.5,   0,    'Elsa Bloodstone',                true),
  ('Hawkeye',                           'Skill',    7.25,  20,   'Hawkeye',                        true),
  ('Misty Knight',                      'Skill',    5.75,  0,    'Misty Knight',                   true),
  ('Gwenpool',                          'Skill',    7.25,  20,   'Gwenpool',                       true),
  ('Pantera Negra',                     'Skill',    7.25,  200,  'Black Panther',                  true),
  ('Garota Esquilo',                    'Skill',    5.75,  20,   'Squirrel Girl',                  true),
  ('Ronin',                             'Skill',    5.75,  0,    'Ronin',                          true),
  ('Korg',                              'Skill',    8,     200,  'Korg',                           true),
  ('Treinador',                         'Skill',    5.75,  200,  'Taskmaster',                     true),
  ('Daredevil (Hell''s Kitchen)',       'Skill',    5.75,  20,   'Daredevil (Hell''s Kitchen)',    true),
  ('Viúva Negra',                       'Skill',    2.5,   200,  'Black Widow',                    true),
  ('Kraven',                            'Skill',    5.75,  20,   'Kraven',                         true),
  ('Karnak',                            'Skill',    5.75,  20,   'Karnak',                         true),
  ('Soldado Invernal',                  'Skill',    5.75,  20,   'Winter Soldier',                 true),
  ('Elektra',                           'Skill',    2.5,   0,    'Elektra',                        true),
  ('Cavaleiro da Lua',                  'Skill',    2.5,   0,    'Moon Knight',                    true),
  ('Daredevil (Clássico)',              'Skill',    5.75,  0,    'Daredevil (Classic)',            true)
ON CONFLICT (name) DO UPDATE SET
  champion_class         = EXCLUDED.champion_class,
  attack_tier_score      = EXCLUDED.attack_tier_score,
  attack_recommended_sig = EXCLUDED.attack_recommended_sig,
  name_en                = EXCLUDED.name_en,
  has_7star              = EXCLUDED.has_7star;
